FROM golang:1.26-alpine AS builder
WORKDIR /app
COPY go.work* ./
COPY backend/go.* ./backend/
COPY client/go.* ./client/
COPY shared/golog/go.* ./shared/golog/
RUN go mod download
COPY backend/ ./backend/
COPY client/ ./client/
COPY shared/golog/ ./shared/golog/
RUN CGO_ENABLED=0 go build -ldflags="-s -w" -o /marte ./backend

FROM alpine:3.21
COPY --from=builder /marte /usr/bin/marte
COPY frontend/ /frontend/
WORKDIR /app
VOLUME /app
EXPOSE 14100 14101
ENTRYPOINT ["/usr/bin/marte"]
